final class BookCodeMap {
  const BookCodeMap._();

  static String normalizeText(String code) {
    final normalized = _textCodes[code];
    if (normalized == null) {
      throw FormatException('Unknown VPL TXT book code: $code');
    }
    return normalized;
  }

  static String normalizeSql(String code) {
    final normalized = _sqlCodes[code];
    if (normalized == null) {
      throw FormatException('Unknown VPL SQL book code: $code');
    }
    return normalized;
  }

  static const _textCodes = <String, String>{
    'GEN': 'GEN',
    'EXO': 'EXO',
    'LEV': 'LEV',
    'NUM': 'NUM',
    'DEU': 'DEU',
    'JOS': 'JOS',
    'JDG': 'JDG',
    'RUT': 'RUT',
    '1SA': '1SA',
    '2SA': '2SA',
    '1KI': '1KI',
    '2KI': '2KI',
    '1CH': '1CH',
    '2CH': '2CH',
    'EZR': 'EZR',
    'NEH': 'NEH',
    'EST': 'EST',
    'JOB': 'JOB',
    'PSA': 'PSA',
    'PRO': 'PRO',
    'ECC': 'ECC',
    'SOL': 'SNG',
    'ISA': 'ISA',
    'JER': 'JER',
    'LAM': 'LAM',
    'EZE': 'EZK',
    'DAN': 'DAN',
    'HOS': 'HOS',
    'JOE': 'JOL',
    'AMO': 'AMO',
    'OBA': 'OBA',
    'JON': 'JON',
    'MIC': 'MIC',
    'NAH': 'NAM',
    'HAB': 'HAB',
    'ZEP': 'ZEP',
    'HAG': 'HAG',
    'ZEC': 'ZEC',
    'MAL': 'MAL',
    'MAT': 'MAT',
    'MAR': 'MRK',
    'LUK': 'LUK',
    'JOH': 'JHN',
    'ACT': 'ACT',
    'ROM': 'ROM',
    '1CO': '1CO',
    '2CO': '2CO',
    'GAL': 'GAL',
    'EPH': 'EPH',
    'PHI': 'PHP',
    'COL': 'COL',
    '1TH': '1TH',
    '2TH': '2TH',
    '1TI': '1TI',
    '2TI': '2TI',
    'TIT': 'TIT',
    'PHM': 'PHM',
    'HEB': 'HEB',
    'JAM': 'JAS',
    '1PE': '1PE',
    '2PE': '2PE',
    '1JO': '1JN',
    '2JO': '2JN',
    '3JO': '3JN',
    'JUD': 'JUD',
    'REV': 'REV',
    '1ES': '1ES',
    '4ES': '4ES',
    '1MA': '1MA',
    '2MA': '2MA',
    '3MA': '3MA',
    '4MA': '4MA',
    'BAR': 'BAR',
    'DNG': 'DAG',
    'ESG': 'ESG',
    'JDT': 'JDT',
    'PRM': 'MAN',
    'PSX': 'PS2',
    'SIR': 'SIR',
    'TOB': 'TOB',
    'WIS': 'WIS',
  };

  static const _sqlCodes = <String, String>{
    'GEN': 'GEN',
    'EXO': 'EXO',
    'LEV': 'LEV',
    'NUM': 'NUM',
    'DEU': 'DEU',
    'JOS': 'JOS',
    'JDG': 'JDG',
    'RUT': 'RUT',
    '1SA': '1SA',
    '2SA': '2SA',
    '1KI': '1KI',
    '2KI': '2KI',
    '1CH': '1CH',
    '2CH': '2CH',
    'EZR': 'EZR',
    'NEH': 'NEH',
    'EST': 'EST',
    'JOB': 'JOB',
    'PSA': 'PSA',
    'PRO': 'PRO',
    'ECC': 'ECC',
    'SNG': 'SNG',
    'ISA': 'ISA',
    'JER': 'JER',
    'LAM': 'LAM',
    'EZK': 'EZK',
    'DAN': 'DAN',
    'HOS': 'HOS',
    'JOL': 'JOL',
    'AMO': 'AMO',
    'OBA': 'OBA',
    'JON': 'JON',
    'MIC': 'MIC',
    'NAM': 'NAM',
    'HAB': 'HAB',
    'ZEP': 'ZEP',
    'HAG': 'HAG',
    'ZEC': 'ZEC',
    'MAL': 'MAL',
    'MAT': 'MAT',
    'MRK': 'MRK',
    'LUK': 'LUK',
    'JHN': 'JHN',
    'ACT': 'ACT',
    'ROM': 'ROM',
    '1CO': '1CO',
    '2CO': '2CO',
    'GAL': 'GAL',
    'EPH': 'EPH',
    'PHP': 'PHP',
    'COL': 'COL',
    '1TH': '1TH',
    '2TH': '2TH',
    '1TI': '1TI',
    '2TI': '2TI',
    'TIT': 'TIT',
    'PHM': 'PHM',
    'HEB': 'HEB',
    'JAS': 'JAS',
    '1PE': '1PE',
    '2PE': '2PE',
    '1JN': '1JN',
    '2JN': '2JN',
    '3JN': '3JN',
    'JUD': 'JUD',
    'REV': 'REV',
    '1ES': '1ES',
    '2ES': '4ES',
    '1MA': '1MA',
    '2MA': '2MA',
    '3MA': '3MA',
    '4MA': '4MA',
    'BAR': 'BAR',
    'DAG': 'DAG',
    'ESG': 'ESG',
    'JDT': 'JDT',
    'MAN': 'MAN',
    'PS2': 'PS2',
    'SIR': 'SIR',
    'TOB': 'TOB',
    'WIS': 'WIS',
  };
}
